FROM quay.io/centos-bootc/centos-bootc:stream10

# Add metadata to container
LABEL org.bootc.image-version="1.0"
LABEL org.bootc.os-type="centos"
LABEL org.bootc.init-system="systemd"

# Install Packages
RUN dnf install -y \
      bootc \
      systemd \
      passwd \
      shadow-utils \
      openssh-server \
      sudo && \
    dnf clean all

# Enable SSH
RUN systemctl enable sshd