FROM quay.io/fedora/fedora-bootc:42

# Add metadata to container
LABEL org.bootc.image-version="1.0"
LABEL org.bootc.os-type="fedora"
LABEL org.bootc.init-system="systemd"

# Install Packages
RUN dnf install -y \
      vim \
      fastfetch && \
    dnf clean all

# Enable SSH
RUN systemctl enable sshd

# Enable auto bootc updates
RUN systemctl enable bootc-fetch-apply-updates.timer