resources:
  - deploy.yaml
  - svc.yaml
  - ingress.yaml
images:
  - name: ghcr.io/cjcocokrisp/blog
    newTag: latest
    digest: sha256:73ee7b135f5969320b6a37e0a2be7a5d62b405d7129a7750c7c81022bda5f43f
