resources:
  - deploy.yaml
  - svc.yaml
  - ingress.yaml
images:
  - name: ghcr.io/cjcocokrisp/blog
    newTag: latest
    digest: sha256:ac9484decafefc474a7f234e7efa7d6ee75e125206de6efc59d7d5ffaa125eb6
