apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pufferpanel-pvc
  namespace: pufferpanel
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
