apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: convertx-data
  namespace: convertx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
