apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: headlamp
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  source:
    chart: headlamp
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    targetRevision: "*.*.*"
    helm: 
      values: |
        service:
          type: NodePort
        nodeSelector:
          machine: bastion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
