apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: minecraft-server
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  source:
    repoURL: https://github.com/cjcocokrisp/homelab
    targetRevision: HEAD
    path: k8s/minecraft-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
