apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db-data
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path