apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-data
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path